[audio]
enable_overdrive = true

[bar]
order = [ "main" ]

    [bar.main]
    background_opacity = 0.5
    capsule = true
    center = [ "workspaces" ]
    end = [
        "privacy",
        "tray",
        "keyboard_layout",
        "brightness",
        "input_volume",
        "output_volume",
        "caffeine",
        "notifications"
    ]
    margin_ends = 50
    padding = 0
    reserve_space = false
    shadow = false
    smart_auto_hide = true
    start = [ "bar", "clock", "media", "bluetooth", "network", "group:g1" ]

        [bar.main.dead_zone.actions]
        middle = "settings-toggle"

        [[bar.main.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "cpu", "RAM" ]
        opacity = 1.0
        padding = 6.0

[brightness]
enable_ddcutil = true
minimum_brightness = 0.0
sync_all_monitors = true

[calendar]
enabled = true

[control_center]
sidebar = "full"

    [control_center.calendar]
    show_week_numbers = true

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "dark_mode"

    [[control_center.shortcuts]]
    type = "caffeine"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
active_monitor_only = true
background_opacity = 0.5
enabled = true
launcher_position = "start"
magnification_scale = 2.0
reserve_space = false
show_dots = true
smart_auto_hide = true

[hot_corners.bottom_left]
action = "launcher"

[hot_corners.bottom_right]
action = "window_switcher"

[hot_corners.top_right]
action = "control_center"

[keybinds]
delete = [ "Delete", "BackSpace" ]
down = [ "Down", "Ctrl+j" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+k" ]

[location]
auto_locate = true

[lockscreen]
allow_empty_password = true

[lockscreen_widgets]
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@DP-6",
    "lockscreen-login-box@HDMI-A-2",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006",
    "lockscreen-widget-0000000000000007"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-6"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-6"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-6".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 974.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 80.0
    box_width = 800.0
    cx = 960.0
    cy = 775.5
    output = "HDMI-A-2"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        clock_style = "digital"
        format = "{:%F %T, %A, %B}"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 368.0
    box_width = 432.0
    cx = 962.0
    cy = 538.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        visualization_mode = "all"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 240.0
    box_width = 496.0
    cx = 296.0
    cy = 948.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "media_player"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 240.0
    box_width = 480.0
    cx = 1616.0
    cy = 940.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 240.0
    box_width = 480.0
    cx = 298.0
    cy = 695.5
    output = "HDMI-A-2"
    rotation = 0.0
    type = "noctalia/timer:desktop"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 224.0
    box_width = 480.0
    cx = 1616.0
    cy = 703.5
    output = "HDMI-A-2"
    rotation = 0.0
    type = "weather"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 192.0
    box_width = 800.0
    cx = 960.0
    cy = 236.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "volume"

[notification]
background_opacity = 1.0
offset_y = 40
position = "top_right"

[osd]
background_opacity = 1.0
offset_y = 40
position = "bottom_center"
position_vertical = "center_right"

[plugin_settings."noctalia/bitwarden"]
clear_clipboard_seconds = 30
login_open_near_click = true
login_placement = "attached"
unlock_open_near_click = true
unlock_placement = "attached"

[plugins]
enabled = [ "noctalia/timer", "noctalia/translator", "noctalia/screen_recorder", "noctalia/bitwarden" ]

    [[plugins.source]]
    enabled = true
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

[shell]
clipboard_history_max_entries = 1000
date_format = "%A, %B, %x"
external_ip_enabled = true
font_family = "DejaVu Sans"
launch_apps_as_systemd_services = true
password_style = "random"
polkit_agent = true
popup_shadows = false
screen_time_enabled = true
telemetry_enabled = true
time_format = "{:%T}"

    [shell.launcher.providers.emoji]
    global = true

    [shell.launcher.providers.session]
    global = true

    [shell.launcher.providers.wallpaper]
    global = true

    [shell.launcher.providers.windows]
    global = true

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    launcher_position = "bottom_center"
    list_item_background = true
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    polkit_placement = "attached"
    shadow = false
    transparency_mode = "glass"

    [shell.screenshot]
    confirm_region = true
    remember_last_region = true
    show_cursor = true

[theme]
custom_palette = "stylix"
mode = "dark"
pure_black_dark = true
source = "custom"

[wallpaper]
directory = "~/Pictures/Wallpapers"
enabled = true
per_monitor_directories = true
transition = [ "fade" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/shemishtamesh/Pictures/Wallpapers/DP-6/wallpaper.png"

    [wallpaper.last]
    path = "/home/shemishtamesh/Pictures/Wallpapers/DP-6/wallpaper.png"

    [wallpaper.monitor.DP-6]
    directory = "/home/shemishtamesh/Pictures/Wallpapers/DP-6"

    [wallpaper.monitor.HDMI-A-1]
    directory = "/home/shemishtamesh/Pictures/Wallpapers/HDMI-A-1"

    [wallpaper.monitor.HDMI-A-2]
    directory = "/home/shemishtamesh/Pictures/Wallpapers/HDMI-A-2"

    [wallpaper.monitors.DP-6]
    path = "/home/shemishtamesh/Pictures/Wallpapers/DP-6/wallpaper.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/shemishtamesh/Pictures/Wallpapers/DP-6/wallpaper.png"

    [wallpaper.monitors.HDMI-A-2]
    path = "/home/shemishtamesh/Pictures/Wallpapers/DP-6/wallpaper.png"

    [[wallpaper.favorite]]
    path = "/home/shemishtamesh/Pictures/Wallpapers/DP-6/wallpaper.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/shemishtamesh/Pictures/Wallpapers/HDMI-A-2/wallpaper.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/shemishtamesh/Pictures/Wallpapers/HDMI-A-1/wallpaper.png"
    theme_mode = "auto"

[widget.RAM]
show_glyph = false
show_value = false
stat = "ram_used"
type = "sysmon"

[widget.bar]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.battery]
enabled = false

[widget.cpu]
show_glyph = false
show_value = false

[widget.nightlight]
enabled = false

[widget.privacy]
hide_inactive = true

[widget.session]
enabled = false

[widget.settings]
enabled = false

[widget.sysmon]
show_glyph = false
show_value = false

[widget.weather]
enabled = false

[widget.workspaces]
display = "name"
empty_color = "on_surface"
hide_when_empty = true
style = "focus_hint"
