system: "base24"
name: "default base24"
slug: "default-base24"
variant: "dark"
palette:
  base00: "#282C34"
  base01: "#3F4451"
  base02: "#4F5666"
  base03: "#545862"
  base04: "#9196A1"
  base05: "#ABB2BF"
  base06: "#E6E6E6"
  base07: "#FFFFFF"
  base08: "#E06C75"
  base09: "#D19A66"
  base0A: "#E5C07B"
  base0B: "#98C379"
  base0C: "#56B6C2"
  base0D: "#61AFEF"
  base0E: "#C678DD"
  base0F: "#BE5046"
  base10: "#21252B"
  base11: "#181A1F"
  base12: "#FF7B86"
  base13: "#EFB074"
  base14: "#B1E18B"
  base15: "#63D4E0"
  base16: "#67CDFF"
  base17: "#E48BFF"
