system: "base24"
name: "snow"
slug: "snow"
author: ""
variant: "dark"
palette:
  base00: "#000000"
  base01: "#09111a"
  base02: "#152535"
  base03: "#1f364c"
  base04: "#4e677e"
  base05: "#75899e"
  base06: "#94a9ba"
  base07: "#b6c0c6"
  base08: "#ff6b6b"
  base09: "#ffab6b"
  base0A: "#f0fa90"
  base0B: "#6af09e"
  base0C: "#8f8fff"
  base0D: "#569dff"
  base0E: "#c3a1ff"
  base0F: "#b48f6a"
  base10: "#ff8f8f"
  base11: "#ffc28f"
  base12: "#ffffaf"
  base13: "#8dffb9"
  base14: "#afafff"
  base15: "#2fbbff"
  base16: "#e5cfff"
  base17: "#d7b18f"
