system: "base24"
name: "IR Black"
slug: "irblack"
author: "Timothée Poisot (edited)"
variant: "dark"
palette:
  base00: "#000000"
  base01: "#242422"
  base02: "#484844"
  base03: "#6c6c66"
  base04: "#918f88"
  base05: "#b5b3aa"
  base06: "#d9d7cc"
  base07: "#fdfbee"
  base08: "#df4c40"
  base09: "#c9a042"
  base0A: "#dfdf96"
  base0B: "#88df40"
  base0C: "#a6a5de"
  base0D: "#76abde"
  base0E: "#df53dd"
  base0F: "#916a1d"
  base10: "#ff6c60"
  base11: "#e9c062"
  base12: "#ffffb6"
  base13: "#a8ff60"
  base14: "#c6c5fe"
  base15: "#96cbfe"
  base16: "#ff73fd"
  base17: "#b18a3d"
