system: "base24"
name: "snow24"
variant: "dark"
palette:
  base11: "#000000"
  base10: "#00000b"
  base00: "#000c0d"
  base01: "#0e1a2f"
  base02: "#3b4e6c"
  base03: "#75899e"
  base04: "#94a9ba"
  base05: "#b6c0c6"
  base06: "#cfe1e7"
  base07: "#ffffff"

  base08: "#ff6b6b"
  base0A: "#f0fa90"
  base0B: "#6af09e"
  base0C: "#80dfdf"
  base0D: "#569dff"
  base0E: "#c3a1ff"
  base0F: "#b48f6a"

  base12: "#ff8f8f"
  base13: "#ffffaf"
  base14: "#8dffb9"
  base15: "#80efef"
  base16: "#a3cfff"
  base17: "#e5cfff"
  base09: "#ffab6b"
