system: "base24"
name: "snow24"
variant: "dark"
palette:
  base00: "#152535"
  base01: "#1f364c"
  base02: "#4e677e"
  base03: "#75899e"
  base04: "#94a9ba"
  base05: "#b6c0c6"
  base06: "#d0d7dd"
  base07: "#e3e7ec"
  base08: "#ff6b6b"
  base09: "#ffab6b"
  base0A: "#f0fa90"
  base0B: "#6af09e"
  base0C: "#80dfdf"
  base0D: "#569dff"
  base0E: "#c3a1ff"
  base0F: "#b48f6a"
  base10: "#09111a"
  base11: "#000000"
  base12: "#ff8f8f"
  base13: "#ffffaf"
  base14: "#8dffb9"
  base15: "#80efef"
  base16: "#a3cfff"
  base17: "#e5cfff"
