system: "base24"
name: "snow24"
variant: "dark"
palette:
  base11: "#000000"
  base10: "#000000"
  base00: "#000000"
  base01: "#2d354f"
  base02: "#3f5765"
  base03: "#6a7f99"
  base04: "#8ca3b5"
  base05: "#a9bdc6"
  base06: "#bcd8e4"
  base07: "#ffffff"

  base08: "#ff6b6b"
  base0A: "#f0fa90"
  base0B: "#6af09e"
  base0C: "#80dfdf"
  base0D: "#569dff"
  base0E: "#c3a1ff"
  base0F: "#b48f6a"

  base12: "#ff8f8f"
  base13: "#ffffaf"
  base14: "#8dffb9"
  base15: "#80efef"
  base16: "#a3cfff"
  base17: "#e5cfff"
  base09: "#ffab6b"
