system: "base24"
name: "snow24"
variant: "dark"
palette:
  base11: "#000000"
  base10: "#000000"
  base00: "#000000"
  base01: "#313b3e"
  base02: "#60757c"
  base03: "#92b6c2"
  base04: "#b9deea"
  base05: "#d1e9f1"
  base06: "#e8f4f8"
  base07: "#ffffff"

  base08: "#ff6b6b"
  base12: "#ff8f8f"

  base0A: "#f0fa90"
  base13: "#ffffaf"

  base0B: "#6af09e"
  base14: "#8dffb9"

  base0C: "#80dfdf"
  base15: "#80efef"

  base0D: "#569dff"
  base16: "#a3cfff"

  base0E: "#c3a1ff"
  base17: "#e5cfff"

  base0F: "#b48f6a"
  base09: "#ffab6b"
